import type { Drive } from '@/types'

export const drives: Drive[] = [
  {
    id: 1,
    name: 'Epic Meaning & Calling',
    chineseName: '史詩意義',
    description: '相信自己正在做比自己更偉大的事情',
    color: 'text-plum',
    bgColor: 'bg-plum-soft',
    borderColor: 'border-plum/30',
    barColor: 'bg-plum',
  },
  {
    id: 2,
    name: 'Development & Accomplishment',
    chineseName: '發展成就',
    description: '進步、技能提升、克服挑戰的內在驅動',
    color: 'text-warm-amber',
    bgColor: 'bg-warm-amber-soft',
    borderColor: 'border-warm-amber/30',
    barColor: 'bg-warm-amber',
  },
  {
    id: 3,
    name: 'Creativity & Feedback',
    chineseName: '創意授權',
    description: '使用創意、解決方案和各種可能性',
    color: 'text-leaf',
    bgColor: 'bg-leaf-soft',
    borderColor: 'border-leaf/30',
    barColor: 'bg-leaf',
  },
  {
    id: 4,
    name: 'Ownership & Possession',
    chineseName: '所有權',
    description: '擁有和控制某些事物的感覺',
    color: 'text-dusk',
    bgColor: 'bg-dusk-soft',
    borderColor: 'border-dusk/30',
    barColor: 'bg-dusk',
  },
  {
    id: 5,
    name: 'Social Influence',
    chineseName: '社會影響',
    description: '社交元素，包括師徒制、社交接受、競爭',
    color: 'text-plum',
    bgColor: 'bg-plum-soft',
    borderColor: 'border-plum/30',
    barColor: 'bg-plum',
  },
  {
    id: 6,
    name: 'Scarcity & Impatience',
    chineseName: '稀缺性',
    description: '想要某樣東西因為很難得到或稀有',
    color: 'text-accent',
    bgColor: 'bg-accent-soft',
    borderColor: 'border-accent/30',
    barColor: 'bg-accent',
  },
  {
    id: 7,
    name: 'Unpredictability & Curiosity',
    chineseName: '不確定性',
    description: '不知道接下來會發生什麼的好奇心',
    color: 'text-dusk',
    bgColor: 'bg-dusk-soft',
    borderColor: 'border-dusk/30',
    barColor: 'bg-dusk',
  },
  {
    id: 8,
    name: 'Loss & Avoidance',
    chineseName: '損失避免',
    description: '避免失去已擁有事物的動機',
    color: 'text-accent',
    bgColor: 'bg-accent-soft',
    borderColor: 'border-accent/30',
    barColor: 'bg-accent',
  },
]
