import type { Drive } from '../types'

export const drives: Drive[] = [
  {
    id: 1,
    name: 'Epic Meaning & Calling',
    chineseName: '史詩意義',
    description: '相信自己正在做比自己更偉大的事情',
    color: 'text-violet-400',
    bgColor: 'bg-violet-500/10',
    borderColor: 'border-violet-500/30',
    barColor: 'bg-violet-500',
  },
  {
    id: 2,
    name: 'Development & Accomplishment',
    chineseName: '發展成就',
    description: '進步、技能提升、克服挑戰的內在驅動',
    color: 'text-amber-400',
    bgColor: 'bg-amber-500/10',
    borderColor: 'border-amber-500/30',
    barColor: 'bg-amber-500',
  },
  {
    id: 3,
    name: 'Creativity & Feedback',
    chineseName: '創意授權',
    description: '使用創意、解決方案和各種可能性',
    color: 'text-emerald-400',
    bgColor: 'bg-emerald-500/10',
    borderColor: 'border-emerald-500/30',
    barColor: 'bg-emerald-500',
  },
  {
    id: 4,
    name: 'Ownership & Possession',
    chineseName: '所有權',
    description: '擁有和控制某些事物的感覺',
    color: 'text-blue-400',
    bgColor: 'bg-blue-500/10',
    borderColor: 'border-blue-500/30',
    barColor: 'bg-blue-500',
  },
  {
    id: 5,
    name: 'Social Influence',
    chineseName: '社會影響',
    description: '社交元素，包括師徒制、社交接受、競爭',
    color: 'text-pink-400',
    bgColor: 'bg-pink-500/10',
    borderColor: 'border-pink-500/30',
    barColor: 'bg-pink-500',
  },
  {
    id: 6,
    name: 'Scarcity & Impatience',
    chineseName: '稀缺性',
    description: '想要某樣東西因為很難得到或稀有',
    color: 'text-orange-400',
    bgColor: 'bg-orange-500/10',
    borderColor: 'border-orange-500/30',
    barColor: 'bg-orange-500',
  },
  {
    id: 7,
    name: 'Unpredictability & Curiosity',
    chineseName: '不確定性',
    description: '不知道接下來會發生什麼的好奇心',
    color: 'text-cyan-400',
    bgColor: 'bg-cyan-500/10',
    borderColor: 'border-cyan-500/30',
    barColor: 'bg-cyan-500',
  },
  {
    id: 8,
    name: 'Loss & Avoidance',
    chineseName: '損失避免',
    description: '避免失去已擁有事物的動機',
    color: 'text-red-400',
    bgColor: 'bg-red-500/10',
    borderColor: 'border-red-500/30',
    barColor: 'bg-red-500',
  },
]
